### ISSUE TITLE
error npm run dev

### ISSUE THREAD

**Issue by adrianodemoura** [jtpdev/anagramador-vue#1]
i have folling error:

$ npm run dev

> anagramador@1.0.0 dev D:\AppNode\Vue\anagramador-vue-master
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 12% building modules 24/36 modules 12 active ...ue\anagramador-vue-master\src\App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.                     94% asset optimization ERROR  Failed to compile with 2 errors14:13:23

These dependencies were not found:

* !!vue-style-loader!css-loader?{"sourceMap":true}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!sass-loader?{"sourceMap":true}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue in ./src/App.vue
* !!vue-style-loader!css-loader?{"sourceMap":true}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-4cb66771","scoped":true,"hasInlineConfig":false}!sass-loader?{"sourceMap":true}!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./Anagramador.vue in ./src/components/Anagramador.vue

To install them, you can run: npm install --save !!vue-style-loader!css-loader?{"sourceMap":true}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!sass-loader?{"sourceMap":true}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue !!vue-style-loader!css-loader?{"sourceMap":true}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-4cb66771","scoped":true,"hasInlineConfig":false}!sass-loader?{"sourceMap":true}!../../node_modules/vue-loader/lib/selector?type=styles&index=0!./Anagramador.vue

**Comment by jtpdev** [comment]
Hi @adrianodemoura, did you try to install the mentionated packages: *npm install --save !!vue-style-loader!css-loader*?
